name: multi_radio_app
description: A radio app with a collection of voice actor radios.

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3 #https://pub.dev/packages/cupertino_icons
  webview_flutter: ^2.0.8 #https://pub.dev/packages/webview_flutter
  # flutter_inappwebview: ^5.3.2 #https://pub.dev/packages/flutter_inappwebview

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
#  assets:
#    - images
